gems:
  - jekyll-redirect-from
  - jekyll-seo-tag

exclude:

array: []

# for SEO
# google_site_verification: 
title: 'Dive with Passion | The world Underwater'
description: 'Follow my travels through the world underwater.'
url: 'http://www.divewithpassion.com'
#author:
#  twitter: openrov

twitter:
  username: divewithpssion

social:
  name: DiveWithPassion
  links:
    - https://twitter.com/divewithpassion
    - https://www.facebook.com/dominik.fretz
    - https://www.instagram.com/divewithpassion
    - https://www.youtube.com/channel/UCcWVgjBiPn1KLkar0VtRsaQ

# logo: /assets/openrov/images/openrov-dark.png



